### ISSUE TITLE
Any planned updates

### ISSUE THREAD

**Issue by jcornwellshiel** [WillPall/MobRepellent#4]
I was getting ready to write a plugin very similar to yours at the request of some of my players, and noticed that yours has plans very similar to my own. I also saw in the other open issue that you're working on a new version. What's the status there? Do you need any help getting it updated or reworking it?

Edit: I guess I should have paid attention to the "month" timeline noted in the other comment ;)

**Comment by WillPall** [comment]
This plugin has been updated to work with version 1.20 of PaperMC (and probably many other servers and versions). Apologies for the _very_ long delay, but hopefully it's useful!
